[package]
name = "ioc_extra"
version = "0.0.1"
edition = "2021"

[dependencies]
jpeg-encoder = { version = "0.6.0" }
ioc_core = { path = "../ioc_core" }
tokio-util = {version = "0.7.10" }
rand = "0.8.5"

tracing.workspace = true
tokio.workspace = true
serde.workspace = true
futures.workspace = true