[package]
name = "ioc"
version = "0.0.1"
edition = "2021"

[features]
rpi = ["dep:ioc_rpi_gpio"]

[dependencies]
ioc_core = { path = "../ioc_core"}
ioc_rpi_gpio = { path = "../ioc_rpi_gpio", optional = true}

tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true