name: Test PR
run-name: Testing a PR by ${{github.actor}}
on: [pull_request]
jobs:
  test:
    name: check cargo fmt, clippy, build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.72.0
          components: clippy rustfmt
      - name: ls 
        run: ls -lha && pwd
      - name: Rustfmt
        working-directory: ioc
        run: cargo fmt -- --check
      - name: Clippy
        working-directory: ioc 
        run: cargo clippy --